export interface Product {
  id: string;
  name: string;
  category: string;
  categoryLabel: string;
  description: string;
  longDescription: string;
  features: string[];
  process: { step: string; desc: string }[];
  minPax: string;
  duration: string;
  image: string;
  badge?: string;
}

export const PRODUCTS: Product[] = [
  {
    id: 'full-concert-production',
    name: 'Full Concert Production',
    category: 'concert',
    categoryLabel: 'Concert & Live Music',
    description: 'Produksi konser lengkap dengan sound system profesional, lighting rig, LED wall, dan stage management.',
    longDescription: 'Layanan produksi konser skala penuh yang mencakup seluruh aspek teknis dan non-teknis. Tim kami menangani dari rigging hingga broadcast, memastikan pengalaman terbaik bagi artis dan penonton.',
    features: ['Main Stage Setup', 'Professional Sound System (line array)', 'Full Lighting Rig', 'LED Video Wall', 'Backstage Management', 'Crowd Barrier & Security Zone', 'Artist Green Room', 'Live Streaming Setup'],
    process: [
      { step: 'Konsultasi', desc: 'Diskusi kebutuhan teknis, venue, dan budget' },
      { step: 'Site Survey', desc: 'Tim kami survei venue dan siapkan technical rider' },
      { step: 'Production', desc: 'Setup rigging, sound, lighting, dan LED' },
      { step: 'Rehearsal', desc: 'Sound check dan lighting cue bersama artis' },
      { step: 'Show Day', desc: 'Eksekusi penuh dengan stage manager & crew' },
    ],
    minPax: 'Min. 500 pax',
    duration: '1–3 hari',
    image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=1200&q=80',
    badge: 'Most Popular',
  },
  {
    id: 'intimate-live-show',
    name: 'Intimate Live Show',
    category: 'concert',
    categoryLabel: 'Concert & Live Music',
    description: 'Pertunjukan live music skala menengah untuk venue indoor dengan atmosfer yang intim dan personal.',
    longDescription: 'Format konser yang lebih personal dan intim, ideal untuk venue berkapasitas 100–1000 penonton. Cocok untuk showcase artis, album launch, atau private concert.',
    features: ['Stage Design Custom', 'In-Ear Monitor System', 'FOH & Monitor Mixing', 'Venue Decoration', 'Photography & Videography', 'Meet & Greet Setup'],
    process: [
      { step: 'Briefing', desc: 'Diskusi konsep dan setlist bersama artis' },
      { step: 'Design', desc: 'Desain stage dan dekorasi sesuai tema' },
      { step: 'Setup', desc: 'Instalasi audio, lighting, dan dekorasi' },
      { step: 'Sound Check', desc: 'Rehearsal dan penyesuaian mix' },
      { step: 'Show', desc: 'Eksekusi acara dengan tim profesional' },
    ],
    minPax: 'Min. 100 pax',
    duration: '1 hari',
    image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80',
  },
  {
    id: 'corporate-gala-dinner',
    name: 'Corporate Gala Dinner',
    category: 'corporate',
    categoryLabel: 'Corporate Event',
    description: 'Malam gala dinner eksklusif dengan dekorasi premium, entertainment, dan manajemen acara profesional.',
    longDescription: 'Gala dinner eksklusif yang dirancang untuk memperkuat brand perusahaan dan menghargai mitra serta karyawan. Setiap detail diperhatikan untuk menciptakan kesan mewah yang tak terlupakan.',
    features: ['Premium Table Setting', 'Backdrop & Dekorasi Custom', 'Live Entertainment', 'Catering Coordination', 'MC Profesional Bilingual', 'Dokumentasi Foto & Video', 'Photo Booth Premium', 'Award Ceremony Setup'],
    process: [
      { step: 'Konsultasi', desc: 'Diskusi tema, budget, dan konsep acara' },
      { step: 'Vendor Selection', desc: 'Seleksi venue, katering, dan entertainer' },
      { step: 'Dekorasi', desc: 'Setup dekorasi dan backdrop H-1' },
      { step: 'Rehearsal', desc: 'Gladi resik rundown bersama MC' },
      { step: 'Event Day', desc: 'Eksekusi penuh dengan event director' },
    ],
    minPax: 'Min. 200 pax',
    duration: '1 hari',
    image: 'https://images.unsplash.com/photo-1560439514-4e9645039924?w=1200&q=80',
    badge: 'Premium',
  },
  {
    id: 'annual-company-event',
    name: 'Annual Company Event',
    category: 'corporate',
    categoryLabel: 'Corporate Event',
    description: 'Event tahunan perusahaan mencakup gathering, awarding ceremony, dan hiburan karyawan.',
    longDescription: 'Event tahunan yang komprehensif untuk mempererat hubungan karyawan, merayakan pencapaian, dan membangun semangat tim. Kami menangani semua aspek dari venue hingga entertainment.',
    features: ['Venue Scouting & Booking', 'Rundown Management', 'Award Ceremony', 'Team Building Activities', 'Photo Booth & Activation', 'Live Music / Band', 'Merchandise Goodie Bag', 'Transportation Coordination'],
    process: [
      { step: 'Planning', desc: 'Kick-off meeting dan timeline project' },
      { step: 'Venue', desc: 'Survey dan booking venue terbaik' },
      { step: 'Content', desc: 'Desain materi, backdrop, dan publikasi' },
      { step: 'Setup', desc: 'Instalasi dekorasi dan equipment' },
      { step: 'Execution', desc: 'Pelaksanaan dengan project manager dedicated' },
    ],
    minPax: 'Min. 150 pax',
    duration: '1–2 hari',
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=1200&q=80',
  },
  {
    id: 'wedding-spectacular',
    name: 'Wedding Spectacular',
    category: 'wedding',
    categoryLabel: 'Wedding & Private',
    description: 'Pernikahan impian dengan dekorasi mewah, entertainment eksklusif, dan koordinasi menyeluruh.',
    longDescription: 'Layanan wedding organizer premium yang menangani setiap momen hari istimewa Anda. Dari dekorasi mewah hingga live orchestra, kami wujudkan pernikahan impian Anda.',
    features: ['Full Floral Decoration', 'Live Band / Orchestra', 'Wedding Coordinator Dedicated', 'Lighting Design Artistik', 'Video Mapping on Stage', 'Bridal Entrance Setup', 'Photo & Video Dokumentasi', 'Catering Coordination'],
    process: [
      { step: 'Konsultasi', desc: 'Diskusi visi, tema, dan anggaran' },
      { step: 'Vendor', desc: 'Kurasi vendor terbaik sesuai selera' },
      { step: 'Trial', desc: 'Mock-up dekorasi dan food tasting' },
      { step: 'H-1', desc: 'Setup penuh dan dekorasi venue' },
      { step: 'Wedding Day', desc: 'Koordinasi penuh dari pagi hingga selesai' },
    ],
    minPax: 'Min. 300 pax',
    duration: '1 hari (+ setup H-1)',
    image: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1200&q=80',
    badge: 'Exclusive',
  },
  {
    id: 'private-party',
    name: 'Private Party',
    category: 'wedding',
    categoryLabel: 'Wedding & Private',
    description: 'Pesta privat eksklusif untuk ulang tahun, anniversary, atau perayaan keluarga.',
    longDescription: 'Rayakan momen spesial bersama orang-orang tercinta dengan pesta privat yang personal dan berkesan. Kami hadirkan suasana exclusive dengan sentuhan personal sesuai kepribadian Anda.',
    features: ['Custom Theme & Concept', 'DJ / Live Acoustic', 'Catering Setup', 'Photo & Video', 'Special Effects (confetti, pyro)', 'Birthday Cake Setup', 'Dekorasi Balon Premium', 'Photo Booth Custom'],
    process: [
      { step: 'Concept', desc: 'Diskusi tema dan referensi inspirasi' },
      { step: 'Planning', desc: 'Kurasi vendor, menu, dan entertainer' },
      { step: 'Setup', desc: 'Instalasi dekorasi dan sound system' },
      { step: 'Party', desc: 'Pelaksanaan dengan event host' },
      { step: 'Wrap Up', desc: 'Beres-beres dan dokumentasi selesai' },
    ],
    minPax: 'Min. 50 pax',
    duration: '1 hari',
    image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=1200&q=80',
  },
  {
    id: 'art-exhibition',
    name: 'Art Exhibition',
    category: 'exhibition',
    categoryLabel: 'Exhibition & Pameran',
    description: 'Pameran seni profesional dengan tata cahaya artistik, signage, dan manajemen pengunjung.',
    longDescription: 'Pameran seni yang dikurasi dengan cermat, menghadirkan pengalaman visual yang mendalam bagi pengunjung. Kami menangani seluruh aspek teknis dan logistik agar seniman bisa fokus pada karyanya.',
    features: ['Gallery Lighting (track light)', 'Artwork Installation & Hanging', 'Opening Ceremony', 'Visitor Management System', 'Catalogue & Signage Design', 'Security & Insurance', 'Press Release & Publikasi'],
    process: [
      { step: 'Kurasi', desc: 'Seleksi karya dan layout pameran' },
      { step: 'Design', desc: 'Desain tata ruang dan pencahayaan' },
      { step: 'Instalasi', desc: 'Pemasangan karya dan signage' },
      { step: 'Opening', desc: 'Upacara pembukaan dengan tamu undangan' },
      { step: 'Operasional', desc: 'Manajemen pengunjung selama pameran' },
    ],
    minPax: 'Min. 50 pax',
    duration: '3–14 hari',
    image: 'https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=1200&q=80',
  },
  {
    id: 'trade-exhibition',
    name: 'Trade Exhibition',
    category: 'exhibition',
    categoryLabel: 'Exhibition & Pameran',
    description: 'Pameran dagang skala besar dengan booth design, sistem registrasi, dan floor management.',
    longDescription: 'Solusi lengkap pameran dagang skala nasional dan internasional. Dari desain booth hingga manajemen ribuan pengunjung, kami pastikan pameran Anda berjalan profesional.',
    features: ['Booth Design & Build', 'Online Registration System', 'Floor Plan Management', 'AV Equipment Rental', 'Cleaning & Maintenance', 'Security Personnel', 'F&B Management', 'Networking Area Setup'],
    process: [
      { step: 'Planning', desc: 'Floor plan dan alokasi booth' },
      { step: 'Design', desc: 'Desain booth dan main stage' },
      { step: 'Build', desc: 'Konstruksi booth dan instalasi' },
      { step: 'Registration', desc: 'Setup sistem registrasi online/onsite' },
      { step: 'Operations', desc: 'Manajemen operasional harian' },
    ],
    minPax: 'Min. 500 pax',
    duration: '2–7 hari',
    image: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=1200&q=80',
  },
  {
    id: 'music-festival',
    name: 'Music Festival',
    category: 'festival',
    categoryLabel: 'Festival & Bazaar',
    description: 'Festival musik multi-stage dengan outdoor setup, food court, dan manajemen kerumunan profesional.',
    longDescription: 'Festival musik skala besar dengan produksi kelas dunia. Multi-stage setup, sistem ticketing, crowd management, dan seluruh infrastruktur event outdoor ditangani oleh tim berpengalaman kami.',
    features: ['Multi-Stage Setup (2–5 stage)', 'Crowd Management & Barrier', 'Food Court Area', 'Security & Medical Team', 'VIP Zone & Hospitality', 'Ticketing System', 'Parking Management', 'Generator & Power Supply'],
    process: [
      { step: 'Feasibility', desc: 'Studi kelayakan venue dan izin' },
      { step: 'Production', desc: 'Detail teknis setiap stage' },
      { step: 'Logistik', desc: 'Koordinasi vendor dan supplier' },
      { step: 'Setup', desc: 'Instalasi H-3 hingga H-1' },
      { step: 'Festival Days', desc: 'Operasional penuh dengan command center' },
    ],
    minPax: 'Min. 2000 pax',
    duration: '2–4 hari',
    image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=1200&q=80',
    badge: 'Large Scale',
  },
  {
    id: 'food-bazaar-festival',
    name: 'Food & Bazaar Festival',
    category: 'festival',
    categoryLabel: 'Festival & Bazaar',
    description: 'Festival kuliner dan bazaar dengan tenant management, dekorasi instagramable, dan live performance.',
    longDescription: 'Festival kuliner dan lifestyle yang mengundang tenant terbaik, menciptakan atmosfer yang instagramable dan menghibur. Cocok untuk brand activation, komunitas, dan pemda.',
    features: ['Tenant Recruitment & Management', 'Instagram Corner & Photo Spot', 'Live Music Performance', 'Signage & Branding Custom', 'Waste Management', 'Social Media Campaign', 'Influencer Partnership'],
    process: [
      { step: 'Konsep', desc: 'Tema dan kuantitas tenant' },
      { step: 'Rekrutmen', desc: 'Seleksi dan onboarding tenant' },
      { step: 'Layout', desc: 'Desain denah dan dekorasi' },
      { step: 'Setup', desc: 'Instalasi booth dan dekorasi' },
      { step: 'Festival', desc: 'Operasional dan entertainment harian' },
    ],
    minPax: 'Min. 1000 pax',
    duration: '2–5 hari',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80',
  },
  {
    id: 'product-launch-event',
    name: 'Product Launch Event',
    category: 'launch',
    categoryLabel: 'Product Launch',
    description: 'Peluncuran produk berkesan dengan staging dramatis, media coverage, dan pengalaman brand immersive.',
    longDescription: 'Ciptakan buzz maksimal untuk produk baru Anda dengan launch event yang dramatis dan berkesan. Kami menggabungkan teknologi, storytelling, dan produksi kelas dunia untuk momen reveal yang tak terlupakan.',
    features: ['Stage & Product Reveal Setup', 'Media & Press Invitation', 'Brand Activation Area', 'Press Kit & Goodie Bag', 'Live Streaming Multi-Platform', 'Influencer & KOL Management', 'Professional Photography', 'Post-Event Report'],
    process: [
      { step: 'Strategy', desc: 'Konsep reveal dan narrative brand' },
      { step: 'Media Plan', desc: 'Undangan media dan influencer' },
      { step: 'Production', desc: 'Desain stage dan AV' },
      { step: 'Rehearsal', desc: 'Gladi resik reveal sequence' },
      { step: 'Launch Day', desc: 'Eksekusi dan live coverage' },
    ],
    minPax: 'Min. 100 pax',
    duration: '1 hari',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&q=80',
    badge: 'Trending',
  },
  {
    id: 'brand-activation',
    name: 'Brand Activation',
    category: 'launch',
    categoryLabel: 'Product Launch',
    description: 'Aktivasi brand di pusat perbelanjaan atau ruang publik untuk menjangkau audiens lebih luas.',
    longDescription: 'Aktivasi brand yang kreatif dan interaktif di lokasi strategis untuk membangun awareness dan engagement langsung dengan konsumen. Kami menciptakan pengalaman yang membekas.',
    features: ['Location Scouting & Permit', 'Interactive Booth Design', 'Sampling & Demo Program', 'Social Media Wall', 'Influencer & MC Support', 'Games & Giveaway', 'Data Collection System', 'Daily Report & Analytics'],
    process: [
      { step: 'Strategy', desc: 'Target audience dan tujuan aktivasi' },
      { step: 'Location', desc: 'Survey dan perizinan lokasi' },
      { step: 'Design', desc: 'Desain booth dan materi branding' },
      { step: 'Setup', desc: 'Instalasi dan pelatihan SPG/SPB' },
      { step: 'Aktivasi', desc: 'Pelaksanaan dan monitoring harian' },
    ],
    minPax: 'Min. 200 pax',
    duration: '1–7 hari',
    image: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=1200&q=80',
  },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
